artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Shrikanthp04/datasets/raw/main/airline_passenger_satisfaction.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/airline_passenger_satisfaction.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/airline_passenger_satisfaction.csv
  target_column: str

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  valid_data_path: artifacts/data_transformation/valid.csv
  models_path: artifacts/model_trainer
  best_model_path: artifacts/model_trainer/best_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json